CommonPython: commonpython.cli.cli Namespace Reference
commonpython.cli.cli Namespace Reference
Classes
class CLI
Functions
argparse.ArgumentParser create_parser ()
main ()
Detailed Description
CLI Interface for CommonPython Framework
Provides command-line interface using only standard Python modules with support for:
- Database operations
- Message queue operations
- Configuration management
- Logging control
- Framework testing
Function Documentation
create_parser()
argparse.ArgumentParser commonpython.cli.cli.create_parser ()
Create command-line argument parser.
@brief Create argument parser for CLI commands.
@return Configured ArgumentParser instance
Definition at line 347 of file cli.py.
def create_parser() -> argparse.ArgumentParser:
    """
    Create command-line argument parser.
    @brief Create argument parser for CLI commands.
    @return Configured ArgumentParser instance
    """
    parser = argparse.ArgumentParser(description='CommonPython Framework CLI')
    parser.add_argument('--config', '-c', help='Configuration file path')
    subparsers = parser.add_subparsers(dest='command', help='Available commands')
    # Database commands
    db_parser = subparsers.add_parser('database', help='Database operations')
    db_subparsers = db_parser.add_subparsers(dest='db_command', help='Database commands')
    db_test_parser = db_subparsers.add_parser('test', help='Test database connection')
    db_exec_parser = db_subparsers.add_parser('execute', help='Execute database query')
    db_exec_parser.add_argument('query', help='SQL query to execute')
    db_exec_parser.add_argument('--params', '-p', help='Query parameters as JSON string')
    db_info_parser = db_subparsers.add_parser('info', help='Get table information')
    db_info_parser.add_argument('table_name', help='Name of the table')
    # Messaging commands
    mq_parser = subparsers.add_parser('messaging', help='Message queue operations')
    mq_subparsers = mq_parser.add_subparsers(dest='mq_command', help='Messaging commands')
    mq_test_parser = mq_subparsers.add_parser('test', help='Test MQ connection')
    mq_get_parser = mq_subparsers.add_parser('get', help='Get message from queue')
    mq_get_parser.add_argument('queue_name', help='Name of the queue')
    mq_get_parser.add_argument('--timeout', '-t', type=int, help='Timeout in seconds')
    mq_put_parser = mq_subparsers.add_parser('put', help='Put message to queue')
    mq_put_parser.add_argument('queue_name', help='Name of the queue')
    mq_put_parser.add_argument('message', help='Message content')
    mq_put_parser.add_argument('--properties', '-p', help='Message properties as JSON string')
    mq_depth_parser = mq_subparsers.add_parser('depth', help='Get queue depth')
    mq_depth_parser.add_argument('queue_name', help='Name of the queue')
    # Configuration commands
    config_parser = subparsers.add_parser('config', help='Configuration management')
    config_subparsers = config_parser.add_subparsers(dest='config_command', help='Configuration commands')
    config_show_parser = config_subparsers.add_parser('show', help='Show current configuration')
    config_get_parser = config_subparsers.add_parser('get', help='Get configuration value')
    config_get_parser.add_argument('key', help='Configuration key')
    config_set_parser = config_subparsers.add_parser('set', help='Set configuration value')
    config_set_parser.add_argument('key', help='Configuration key')
    config_set_parser.add_argument('value', help='Configuration value')
    # Test all command
    subparsers.add_parser('test-all', help='Test all framework components')
    return parser
Referenced by commonpython.cli.cli.main().
main()
commonpython.cli.cli.main ()
Main CLI entry point.
@brief Main entry point for CLI application.
Definition at line 409 of file cli.py.
def main():
    """
    Main CLI entry point.
    @brief Main entry point for CLI application.
    """
    parser = create_parser()
    args = parser.parse_args()
    if not args.command:
        parser.print_help()
        return
    cli = None
    try:
        if args.command != 'help':
            cli = CLI(args.config)
        if args.command == 'database':
            if args.db_command == 'test':
                cli.test_database()
            elif args.db_command == 'execute':
                cli.execute_query(args.query, args.params)
            elif args.db_command == 'info':
                cli.get_table_info(args.table_name)
        elif args.command == 'messaging':
            if args.mq_command == 'test':
                cli.test_messaging()
            elif args.mq_command == 'get':
                cli.get_message(args.queue_name, args.timeout)
            elif args.mq_command == 'put':
                cli.put_message(args.queue_name, args.message, args.properties)
            elif args.mq_command == 'depth':
                cli.get_queue_depth(args.queue_name)
        elif args.command == 'config':
            if args.config_command == 'show':
                cli.show_config()
            elif args.config_command == 'get':
                cli.get_config(args.key)
            elif args.config_command == 'set':
                cli.set_config(args.key, args.value)
        elif args.command == 'test-all':
            cli.test_all()
    except KeyboardInterrupt:
        print("\nOperation cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"Error: {str(e)}")
        sys.exit(1)
References commonpython.cli.cli.create_parser(), and commonpython.cli.cli.main().
Referenced by commonpython.cli.cli.main().