CommonPython: commonpython.config.config_manager.ConfigManager Class Reference
commonpython.config.config_manager.ConfigManager Class Reference
Public Member Functions
__init__ (self, Optional[str] config_file=None, Optional[str] env_file=None)
Any get (self, str key, Any default=None, bool required=False)
None set (self, str key, Any value)
Dict[str, Any] get_database_config (self)
Dict[str, Any] get_messaging_config (self)
Dict[str, Any] get_logging_config (self)
None reload (self)
Dict[str, Any] to_dict (self)
None save_to_file (self, str file_path)
Protected Member Functions
None _load_config (self)
None _load_from_env (self)
None _set_nested_value (self, str path, Any value)
Protected Attributes
_config_file
_config
Detailed Description
Centralized configuration management for the CommonPython framework.
Supports multiple configuration sources with priority order:
1. Environment variables
2. Configuration files
3. Default values
Definition at line 17 of file config_manager.py.
Constructor & Destructor Documentation
__init__()
commonpython.config.config_manager.ConfigManager.__init__ (self, Optional[str] config_file = None, Optional[str] env_file = None)
Initialize the configuration manager.
@brief Initialize configuration manager with file and environment variable support.
@param config_file Path to YAML configuration file
@param env_file Path to .env file for environment variables (not used in stdlib version)
Definition at line 27 of file config_manager.py.
    def __init__(self, config_file: Optional[str] = None, env_file: Optional[str] = None):
        """
        Initialize the configuration manager.
        @brief Initialize configuration manager with file and environment variable support.
        @param config_file Path to YAML configuration file
        @param env_file Path to .env file for environment variables (not used in stdlib version)
        """
        self._config: Dict[str, Any] = {}
        self._config_file = config_file
        # Load configuration
        self._load_config()
References commonpython.config.config_manager.ConfigManager._config.
Member Function Documentation
_load_config()
None commonpython.config.config_manager.ConfigManager._load_config (self) protected
Load configuration from file and environment variables. Only fail if config_file is provided and missing.
Definition at line 41 of file config_manager.py.
    def _load_config(self) -> None:
        """
        Load configuration from file and environment variables. Only fail if config_file is provided and missing.
        """
        if self._config_file:
            if not os.path.exists(self._config_file):
                raise FileNotFoundError(f"Configuration file '{self._config_file}' not found.")
            with open(self._config_file, 'r', encoding='utf-8') as file:
                self._config = yaml.safe_load(file) or {}
        self._load_from_env()
References commonpython.config.config_manager.ConfigManager._config_file.
Referenced by commonpython.config.config_manager.ConfigManager.reload().
_load_from_env()
None commonpython.config.config_manager.ConfigManager._load_from_env (self) protected
Load configuration from environment variables.
@brief Load configuration values from environment variables.
Definition at line 52 of file config_manager.py.
    def _load_from_env(self) -> None:
        """
        Load configuration from environment variables.
        @brief Load configuration values from environment variables.
        """
        env_mappings = {
            'DB2_HOST': 'database.host',
            'DB2_PORT': 'database.port',
            'DB2_DATABASE': 'database.name',
            'DB2_USER': 'database.user',
            'DB2_PASSWORD': 'database.password',
            'MQ_HOST': 'messaging.host',
            'MQ_PORT': 'messaging.port',
            'MQ_QUEUE_MANAGER': 'messaging.queue_manager',
            'MQ_CHANNEL': 'messaging.channel',
            'LOG_LEVEL': 'logging.level',
            'LOG_FILE': 'logging.file',
            'LOG_FORMAT': 'logging.format'
        }
        for env_var, config_path in env_mappings.items():
            value = os.getenv(env_var)
            if value is not None:
                self._set_nested_value(config_path, value)
References commonpython.config.config_manager.ConfigManager._set_nested_value().
_set_nested_value()
None commonpython.config.config_manager.ConfigManager._set_nested_value (self, str path, Any value) protected
Set a nested configuration value using dot notation.
@brief Set configuration value using dot notation path.
@param path Dot-separated path to configuration value
@param value Value to set
Definition at line 78 of file config_manager.py.
    def _set_nested_value(self, path: str, value: Any) -> None:
        """
        Set a nested configuration value using dot notation.
        @brief Set configuration value using dot notation path.
        @param path Dot-separated path to configuration value
        @param value Value to set
        """
        keys = path.split('.')
        current = self._config
        for key in keys[:-1]:
            if key not in current:
                current[key] = {}
            current = current[key]
        # Convert string values to appropriate types
        if isinstance(value, str):
            if value.lower() in ('true', 'false'):
                value = value.lower() == 'true'
            elif value.isdigit():
                value = int(value)
            elif value.replace('.', '', 1).isdigit():
                value = float(value)
        current[keys[-1]] = value
References commonpython.config.config_manager.ConfigManager._config.
Referenced by commonpython.config.config_manager.ConfigManager._load_from_env(), and commonpython.config.config_manager.ConfigManager.set().
get()
Any commonpython.config.config_manager.ConfigManager.get (self, str key, Any default = None, bool required = False)
Get a configuration value using dot notation. If required and missing, raise KeyError.
Definition at line 105 of file config_manager.py.
    def get(self, key: str, default: Any = None, required: bool = False) -> Any:
        """
        Get a configuration value using dot notation. If required and missing, raise KeyError.
        """
        keys = key.split('.')
        current = self._config
        try:
            for key_part in keys:
                current = current[key_part]
            if current is None and required:
                raise KeyError(f"Required config key '{key}' is missing.")
            return current
        except (KeyError, TypeError):
            if required:
                raise KeyError(f"Required config key '{key}' is missing.")
            return default
References commonpython.config.config_manager.ConfigManager._config.
Referenced by commonpython.config.config_manager.ConfigManager.get_database_config(), commonpython.config.config_manager.ConfigManager.get_logging_config(), and commonpython.config.config_manager.ConfigManager.get_messaging_config().
get_database_config()
Dict[str, Any] commonpython.config.config_manager.ConfigManager.get_database_config (self)
Get database configuration with defaults.
@brief Get database configuration with default values if not specified.
@return Database configuration dictionary
Definition at line 132 of file config_manager.py.
    def get_database_config(self) -> Dict[str, Any]:
        """
        Get database configuration with defaults.
        @brief Get database configuration with default values if not specified.
        @return Database configuration dictionary
        """
        config = {}
        db_defaults = {
            'host': 'localhost',
            'port': 50000,
            'name': 'testdb',
            'user': 'db2inst1',
            'password': '',
            'schema': '',
            'timeout': 30
        }
        for key, default_value in db_defaults.items():
            config[key] = self.get(f'database.{key}', default_value)
        return config
References commonpython.config.config_manager.ConfigManager.get().
get_logging_config()
Dict[str, Any] commonpython.config.config_manager.ConfigManager.get_logging_config (self)
Get logging configuration with defaults.
@brief Get logging configuration with default values if not specified.
@return Logging configuration dictionary
Definition at line 174 of file config_manager.py.
    def get_logging_config(self) -> Dict[str, Any]:
        """
        Get logging configuration with defaults.
        @brief Get logging configuration with default values if not specified.
        @return Logging configuration dictionary
        """
        config = {}
        logging_defaults = {
            'level': 'INFO',
            'file': 'app.log',
            'format': '%(asctime)s - %(name)s - %(levelname)s - %(message)s',
            'max_size': 10485760,
            'backup_count': 5,
            'dir': 'log',
            'colored': True,
            'json_format': False,
            'console': True
        }
        for key, default_value in logging_defaults.items():
            config[key] = self.get(f'logging.{key}', default_value)
        return config
References commonpython.config.config_manager.ConfigManager.get().
get_messaging_config()
Dict[str, Any] commonpython.config.config_manager.ConfigManager.get_messaging_config (self)
Get messaging configuration with defaults.
@brief Get messaging configuration with default values if not specified.
@return Messaging configuration dictionary
Definition at line 153 of file config_manager.py.
    def get_messaging_config(self) -> Dict[str, Any]:
        """
        Get messaging configuration with defaults.
        @brief Get messaging configuration with default values if not specified.
        @return Messaging configuration dictionary
        """
        config = {}
        mq_defaults = {
            'host': 'localhost',
            'port': 1414,
            'queue_manager': 'QM1',
            'channel': 'SYSTEM.DEF.SVRCONN',
            'user': 'mquser',
            'password': '',
            'timeout': 30
        }
        for key, default_value in mq_defaults.items():
            config[key] = self.get(f'messaging.{key}', default_value)
        return config
References commonpython.config.config_manager.ConfigManager.get().
reload()
None commonpython.config.config_manager.ConfigManager.reload (self)
Reload configuration from files and environment.
@brief Reload configuration from all sources.
Definition at line 197 of file config_manager.py.
    def reload(self) -> None:
        """
        Reload configuration from files and environment.
        @brief Reload configuration from all sources.
        """
        self._config = {}
        self._load_config()
References commonpython.config.config_manager.ConfigManager._config, and commonpython.config.config_manager.ConfigManager._load_config().
save_to_file()
None commonpython.config.config_manager.ConfigManager.save_to_file (self, str file_path)
Save current configuration to a YAML file.
@brief Save configuration to YAML file.
@param file_path Path to save configuration file
Definition at line 215 of file config_manager.py.
    def save_to_file(self, file_path: str) -> None:
        """
        Save current configuration to a YAML file.
        @brief Save configuration to YAML file.
        @param file_path Path to save configuration file
        """
        with open(file_path, 'w', encoding='utf-8') as file:
            yaml.dump(self._config, file, default_flow_style=False, indent=2)
References commonpython.config.config_manager.ConfigManager._config.
set()
None commonpython.config.config_manager.ConfigManager.set (self, str key, Any value)
Set a configuration value using dot notation.
@brief Set configuration value by key path.
@param key Configuration key (e.g., 'database.host')
@param value Value to set
Definition at line 122 of file config_manager.py.
    def set(self, key: str, value: Any) -> None:
        """
        Set a configuration value using dot notation.
        @brief Set configuration value by key path.
        @param key Configuration key (e.g., 'database.host')
        @param value Value to set
        """
        self._set_nested_value(key, value)
References commonpython.config.config_manager.ConfigManager._set_nested_value().
to_dict()
Dict[str, Any] commonpython.config.config_manager.ConfigManager.to_dict (self)
Get the entire configuration as a dictionary.
@brief Get complete configuration as dictionary.
@return Dictionary containing all configuration values
Definition at line 206 of file config_manager.py.
    def to_dict(self) -> Dict[str, Any]:
        """
        Get the entire configuration as a dictionary.
        @brief Get complete configuration as dictionary.
        @return Dictionary containing all configuration values
        """
        return self._config.copy()
References commonpython.config.config_manager.ConfigManager._config.
Member Data Documentation
_config
commonpython.config.config_manager.ConfigManager._config protected
Definition at line 49 of file config_manager.py.
Referenced by commonpython.config.config_manager.ConfigManager.__init__(), commonpython.config.config_manager.ConfigManager._set_nested_value(), commonpython.config.config_manager.ConfigManager.get(), commonpython.config.config_manager.ConfigManager.reload(), commonpython.config.config_manager.ConfigManager.save_to_file(), and commonpython.config.config_manager.ConfigManager.to_dict().
_config_file
commonpython.config.config_manager.ConfigManager._config_file protected
Definition at line 36 of file config_manager.py.
Referenced by commonpython.config.config_manager.ConfigManager._load_config().
The documentation for this class was generated from the following file:
commonpython/config/config_manager.py