# Component Configuration Example
# This configuration file demonstrates how components can be configured

# Database configuration
database:
  host: localhost
  port: 50000
  name: component_db
  user: db2inst1
  password: password
  schema: components
  timeout: 30

# Messaging configuration
messaging:
  host: localhost
  port: 1414
  queue_manager: COMPONENT_QM
  channel: SYSTEM.DEF.SVRCONN
  user: mquser
  password: mqpass
  timeout: 30

# Logging configuration
logging:
  level: INFO
  file: component.log
  dir: log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  max_size: 10485760  # 10MB
  backup_count: 5
  colored: true
  json_format: false

# Component-specific configurations
component:
  # Simple component configuration
  operation_count: 10
  delay_seconds: 2

  # Database component configuration
  table_name: events
  operation_type: select  # select, insert, update, delete

  # Messaging component configuration
  queue_name: COMPONENT.QUEUE
  message_count: 5

  # Integrated component configuration
  batch_size: 3
  processing_delay: 1
