# CommonPython Framework Configuration
# Copy this file to your project and modify as needed

# Database configuration for IBM DB2
database:
  host: localhost
  port: 50000
  name: testdb
  user: db2inst1
  password: password
  schema: myschema
  timeout: 30

# Messaging configuration for IBM MQ
messaging:
  host: localhost
  port: 1414
  queue_manager: QM1
  channel: SYSTEM.DEF.SVRCONN
  user: mquser
  password: mqpass
  timeout: 30

# Logging configuration
logging:
  level: INFO
  file: app.log
  dir: log
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_size: 10485760  # 10MB
  backup_count: 5
  colored: true
  json_format: false  # Set to true for JSON format
  console: true

# Component-specific configurations (optional)
component:
  # Add your component-specific settings here
  operation_count: 10
  delay_seconds: 2
  table_name: events
  queue_name: COMPONENT.QUEUE
